_target_: graph_condenser.models.gcond.GCond

defaults:
  - gnn: gcn
  - validator: gcn
  - tester: gcn

lr_model: 1e-2
wd_model: 5e-4
lr_val: 1e-2
wd_val: 5e-4
lr_test: 1e-2
wd_test: 5e-4

observe_mode: transductive
budget: 30
label_distribution: original
init_method: kcenter

structure_generator: null

opt_adj: null

opt_feat:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 3e-4

loop_outer: 1
loop_inner: 0

update_epoch_adj: 0
update_epoch_feat: 0

dis_metric: ours



