_target_: graph_condenser.models.sfgc.SFGC

observe_mode: transductive
budget: 30
label_distribution: original # original, balanced, strict
init_method: kCenter # kCenter, randomChoice

# teacher models' trajectories
traj_buffer:
  _target_: graph_condenser.models.components.trajectories.TrajectoryBuffer
  model: gcn
  dropout: 0.5
  lr: 0.001
  wd: 5e-4
  epochs: 1000
  param_save_interval: 10
  traj_save_interval: 10
  load_all: false
  max_files: null
  max_experts: null
  traj_dir: ${paths.data_dir}/traj/${dataset.dataset_name}
  device: cuda:0

val_mode: GNN
gnn_val:
  _target_: graph_condenser.models.backbones.gcn.GCN
  _partial_: true
  dropout: 0.5
lr_val: 1e-2
wd_val: 5e-4

gnn_test:
  _target_: graph_condenser.models.backbones.gcn.GCN
  _partial_: true
  dropout: 0.5
lr_test: 1e-2
wd_test: 5e-4

# student model
gnn:
  _target_: graph_condenser.models.backbones.gcn.GCN
  _partial_: true
  hid_size: 256
  nlayers: 2
  dropout: 0.0
lr_model: 1.0

opt_feat:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 3e-4

optim_lr: null # Adam, SGD, null
lr_lr: 1e-6
rand_start: true
start_epoch: 30
syn_steps: 90
expert_epochs: 230
