# @package _global_

defaults:
  - override /hydra/sweeper: optuna

optimized_metric: "val/acc_best"

hydra:
  mode: "MULTIRUN"

  sweeper:
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper
    storage: null
    study_name: null
    n_jobs: 1
    direction: maximize
    n_trials: 30
    sampler:
      _target_: optuna.samplers.TPESampler
      seed: 1024
      consider_prior: true
      prior_weight: 1.0
      consider_magic_clip: true
      consider_endpoints: false
      n_startup_trials: 10
      multivariate: false
      warn_independent_sampling: true

    params:
      condenser.opt_adj.lr: tag(log, interval(1e-5, 1.0))
      condenser.opt_feat.lr: tag(log, interval(1e-5, 1.0))
