# @package _global_

hydra:
  mode: "MULTIRUN"
  sweeper:
    params:
      condenser.lr_model: 1e-4,1e-3,1e-2,1e-1,1.0
      condenser.opt_feat.lr: 1e-4,1e-3,1e-2,1e-1,1.0

      condenser.start_epoch: 0,10,20,30,40
      condenser.syn_steps: 100,150,200,250,300
      condenser.expert_epochs: 500,600,700,800,900
