# @package _global_

hydra:
  mode: "MULTIRUN"
  sweeper:
    params:
      condenser.structure_generator.nhid: 64
      condenser.structure_generator.nlayers: 2
      condenser.opt_adj.lr: 1e-2,1e-1
      condenser.opt_feat.lr: 1e-2,1e-1

      condenser.loop_outer: 2,5,10
      condenser.loop_inner: 1,5,10
