_target_: graph_condenser.models.sgdd.SGDD

defaults:
  - gnn: gcn
  - validator: gcn
  - tester: gcn

lr_model: 1e-2
wd_model: 5e-4
lr_val: 1e-2
wd_val: 5e-4
lr_test: 1e-2
wd_test: 5e-4

observe_mode: transductive
budget: 30
label_distribution: original
init_method: kcenter

structure_generator:
  _target_: graph_condenser.models.components.ignr.IGNR
  _partial_: true
  nhid: 128
  ep_ratio: 0.5
  sinkhorn_iter: 5
  nlayers: 3

opt_adj:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 1e-4

opt_feat:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 1e-4

loop_outer: 5
loop_inner: 10

update_epoch_adj: 10
update_epoch_feat: 20

dis_metric: ours

beta: 0.1
opt_scale: 1e-10
