defaults:
  - _self_
  - condenser: dm
  - callbacks: default
  - trainer: default
  - paths: default
  - hparams_search: null

seed: 1024

dataset_name: "arxiv"
dataset_dir: "data"
cls_per_graph: 2
split_ratio: 0.6

wandb: null